FROM node:20-alpine AS build

WORKDIR /app

COPY web/package.json web/package-lock.json* ./
RUN npm ci

COPY web/ .
RUN npm run build

FROM nginx:alpine

RUN adduser -D -g '' app
COPY --from=build /app/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

USER app

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
